

# ? Add database name directly into the URI
spring.data.mongodb.uri=mongodb+srv://miles:miles2003@bookstore.xlwndol.mongodb.net/BookStoreDatabase?retryWrites=true&w=majority&appName=BookStore


# MongoDB database name to use
spring.data.mongodb.database=BookStoreDatabase
